repos:
- hooks:
  - id: seed-isort-config
    language_version: python3.10
  repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
- hooks:
  - id: isort
    language_version: python3.10
  repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
- hooks:
  - id: black
    language_version: python3.10
  repo: https://github.com/ambv/black
  rev: 22.3.0
- hooks:
  - id: check-added-large-files
    language_version: python3.10
  - id: check-ast
    language_version: python3.10
  - id: check-builtin-literals
    language_version: python3.10
  - id: check-case-conflict
    language_version: python3.10
  - id: check-docstring-first
    language_version: python3.10
  - id: check-merge-conflict
    exclude: "docs/.*|\n"
    language_version: python3.10
  - id: check-toml
    language_version: python3.10
  - id: check-yaml
    language_version: python3.10
  - id: debug-statements
    language_version: python3.10
  - id: detect-private-key
    language_version: python3.10
  - id: end-of-file-fixer
    language_version: python3.10
  - id: fix-byte-order-marker
    language_version: python3.10
  - id: fix-encoding-pragma
    language_version: python3.10
  - id: mixed-line-ending
    language_version: python3.10
  - id: pretty-format-json
    language_version: python3.10
  - id: trailing-whitespace
    language_version: python3.10
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
- hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear == 21.11.29]
    exclude: "(?x)^(\n    config/.*|\n    docs/.*|\n    pyproject.toml|\n    .*/tests/.*|\n    .*/migrations/.*|\n)$"
    language_version: python3.10
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - id: pyupgrade
    language_version: python3.10
  repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
- hooks:
  - id: python-safety-dependencies-check
    language_version: python3.10
    args: [--ignore=48542]
  repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.4
- hooks:
  - id: check-gitlab-ci
    stages: [commit-msg]
  repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
- hooks:
  - id: pylint
    entry: pylint
    exclude: "(?x)^(\n    config/.*|\n    docs/.*|\n    pyproject.toml|\n    .*/tests/.*|\n    .*/migrations/.*|\n)$"
    language_version: python3.10
  repo: https://github.com/pre-commit/mirrors-pylint.git
  rev: v3.0.0a4
- hooks:
  - id: mypy
    additional_dependencies: [
      types-pytz==2021.3.3,
      types-Jinja2==2.11.9,
      types-cryptography==3.3.10,
      types-retry==0.9.2,
      types-aiofiles==0.8.0,
      types-python-slugify==5.0.2,
      types-setuptools==57.4.10
    ]
    exclude: "(?x)^(\n    .*/tests/.*|\n    .*/migrations/.*|\n    docs/.*|\n    ^conftest.py|\n)$"
    language_version: python3.10
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
- hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.1.0]
    language_version: python3.10
  repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
- hooks:
  - id: bandit
    exclude: "(?x)^(\n    .*/tests/.*|\n    ^daive/dashboards/mocks/.*|\n    .*/migrations/.*|\n)$"
    language_version: python3.10
  repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
