version: "3.9"

volumes:
  db_volume:

services:
  app:
    container_name: bookabode
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "8000:5000"
    depends_on:
      - db

  db:
      container_name: postgres
      image: postgres:14.2-alpine
      env_file:
        - .env
      ports:
        - 5432:5432
      volumes:
        - db_volume:/var/lib/postgresql/data/
